# Generated by Django 2.2.5 on 2021-05-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_productimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactname', models.CharField(max_length=30)),
                ('contactemail', models.EmailField(max_length=254)),
                ('contactissuetype', models.IntegerField(choices=[[0, 'Consulta'], [1, 'Reclamación'], [2, 'Sugerencia'], [3, 'Información']])),
                ('contactmessage', models.TextField()),
            ],
        ),
    ]
